#!/bin/bash

echo -e "\nWill install Pyrite application files to /usr/share/pyrite/"
echo "Press Enter to accept; otherwise enter a different dir, e.g., /home/$USER/.local/share/pyrite/"
read -p ": " install_dir
[[ -z $install_dir ]] && install_dir=/usr/share/pyrite || install_dir=${install_dir%/}
if [[ -d $install_dir ]]; then
    echo "Directory '$install_dir' already exists."
    echo "All files in directory will be deleted prior to copying new pyrite files."
    read -p "Continue? [y/n] "
    [[ $REPLY != y ]] && exit
else
    if ! mkdir -vp "$install_dir"; then
        echo "Could not create directory '$install_dir'"
        if [[ ! -w ${install_dir%/*} ]]; then
            echo "Need write permission to mkdir in '${install_dir%/*}'"
            echo "Re-run this script as root, i.e., 'sudo $0' or 'su -c $0'"
        fi
        exit 1
    fi
fi
echo OK


echo -e "\nWill install a symlink ('pyrite') to /usr/bin/"
echo "Press Enter to accept; otherwise enter a different dir, e.g., /home/$USER/bin/"
read -p ": " bin_dir
[[ -z $bin_dir ]] && bin_dir=/usr/bin
if [[ ! -w $bin_dir ]]; then
    echo "Need write permission to create symlink in '$bin_dir'"
    echo "Re-run this script as root, i.e., 'sudo $0' or 'su -c $0'"
    exit 2
fi
echo OK


echo -e "\nWill install a desktop shortcut ('pyrite.desktop') to /usr/share/applications/"
echo "Press Enter to accept; otherwise enter a different dir, e.g., /home/$USER/.local/share/applications/"
read -p ": " shortcut_dir
[[ -z $shortcut_dir ]] && shortcut_dir=/usr/share/applications
if [[ ! -w $shortcut_dir ]]; then
    echo "Need write permission to create desktop shortcut in '$shortcut_dir'"
    echo "Re-run this script as root, i.e., 'sudo $0' or 'su -c $0'"
    exit 3
fi
echo OK


echo -e "\nReady to copy files. Last chance to cancel with Ctrl-c. Enter to continue."
read -p ": "

rm -rv "$install_dir"/*

cp -rv --preserve=mode,timestamps modules ui pyrite.py "$install_dir"
sed -i "/^assetdir.*=/s,'','$install_dir/'," "$install_dir/modules/core.py"

cp -v --preserve=mode,timestamps pyrite.desktop "$shortcut_dir"
echo -n "Creating symlink: "
ln -vsf "$install_dir/pyrite.py" "$bin_dir/pyrite"

echo -e "\nFinished!\nRun Pyrite from a terminal as simply 'pyrite', or find the desktop shortcut in your applications menu."
